const products=[
{id:1,name:'Classic Beef Burger',cat:'Burgers',price:249,img:'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=900&q=85',desc:'Smash-style beef patty, melted cheese, crisp lettuce and signature sauce.',tag:'Popular',ingredients:'Beef patty, brioche bun, cheese, lettuce, tomato, signature sauce.'},
{id:2,name:'Double Cheese Burger',cat:'Burgers',price:329,img:'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=900&q=85',desc:'Two juicy patties, double cheese and a bold house sauce.',tag:'Best Seller',ingredients:'2 beef patties, double cheese, onion, pickles, house sauce.'},
{id:3,name:'Crispy Chicken Burger',cat:'Burgers',price:279,img:'https://images.unsplash.com/photo-1606755962773-d324e0a13086?auto=format&fit=crop&w=900&q=85',desc:'Crunchy chicken, fresh slaw and creamy sauce in a toasted bun.',tag:'Popular',ingredients:'Crispy chicken, slaw, lettuce, mayo, brioche bun.'},
{id:4,name:'Spicy Chicken Burger',cat:'Burgers',price:289,img:'https://images.unsplash.com/photo-1615297928064-24977384d0b1?auto=format&fit=crop&w=900&q=85',desc:'Crispy chicken with spicy sauce and fresh crunchy toppings.',tag:'',ingredients:'Spicy crispy chicken, lettuce, jalapeño, spicy sauce.'},
{id:5,name:'BBQ Beef Burger',cat:'Burgers',price:299,img:'https://images.unsplash.com/photo-1553979459-d2229ba7433a?auto=format&fit=crop&w=900&q=85',desc:'Charred beef, smoky BBQ sauce, onion and melted cheese.',tag:'',ingredients:'Beef patty, cheese, BBQ sauce, grilled onion.'},
{id:6,name:'Mega Burger',cat:'Burgers',price:399,img:'https://images.unsplash.com/photo-1550547660-d9450f859349?auto=format&fit=crop&w=900&q=85',desc:'The full stack for serious hunger: double beef, cheese and loaded toppings.',tag:'Best Seller',ingredients:'2 beef patties, cheese, lettuce, tomato, onion, pickles, sauce.'},
{id:7,name:'Classic Burger Combo',cat:'Combos',price:379,img:'https://images.unsplash.com/photo-1571091718767-18b5b1457add?auto=format&fit=crop&w=900&q=85',desc:'Classic burger with fries and a soft drink.',tag:'',ingredients:'Classic burger, fries, soft drink.'},
{id:8,name:'Double Burger Combo',cat:'Combos',price:449,img:'https://images.unsplash.com/photo-1572802419224-296b0aeee0d9?auto=format&fit=crop&w=900&q=85',desc:'Double cheese burger, fries and a soft drink.',tag:'Popular',ingredients:'Double cheese burger, fries, soft drink.'},
{id:9,name:'Chicken Combo',cat:'Combos',price:419,img:'https://images.unsplash.com/photo-1562967916-eb82221dfb92?auto=format&fit=crop&w=900&q=85',desc:'Crispy chicken burger, fries and a soft drink.',tag:'',ingredients:'Chicken burger, fries, soft drink.'},
{id:10,name:'Family Combo',cat:'Combos',price:899,img:'https://images.unsplash.com/photo-1600891964092-4316c288032e?auto=format&fit=crop&w=900&q=85',desc:'A shareable mix of burgers, sides and drinks.',tag:'',ingredients:'2 burgers, chicken bites, fries, 2 drinks.'},
{id:11,name:'French Fries',cat:'Fries',price:129,img:'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=900&q=85',desc:'Golden, crisp fries with a light seasoning.',tag:'',ingredients:'Potatoes, oil, seasoning.'},
{id:12,name:'Loaded Fries',cat:'Fries',price:199,img:'https://images.unsplash.com/photo-1585109649139-366815a0d713?auto=format&fit=crop&w=900&q=85',desc:'Crispy fries loaded with cheese and signature sauce.',tag:'Popular',ingredients:'Fries, cheese sauce, signature sauce, seasoning.'},
{id:13,name:'Chicken Nuggets',cat:'Chicken',price:179,img:'https://images.unsplash.com/photo-1562967914-608f82629710?auto=format&fit=crop&w=900&q=85',desc:'Crispy bite-sized chicken served with dipping sauce.',tag:'',ingredients:'Chicken, crumb coating, seasoning, dip.'},
{id:14,name:'Onion Rings',cat:'Chicken',price:149,img:'https://images.unsplash.com/photo-1639024471283-03518883512d?auto=format&fit=crop&w=900&q=85',desc:'Crunchy golden onion rings with a creamy dip.',tag:'',ingredients:'Onion, batter, seasoning, dip.'},
{id:15,name:'Coca-Cola',cat:'Drinks',price:79,img:'https://images.unsplash.com/photo-1629203849820-fdd70d49c38e?auto=format&fit=crop&w=900&q=85',desc:'Chilled soft drink.',tag:'',ingredients:'Coca-Cola.'},
{id:16,name:'Fresh Lemonade',cat:'Drinks',price:99,img:'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=900&q=85',desc:'Bright, refreshing lemonade.',tag:'',ingredients:'Lemon, water, sugar, ice.'},
{id:17,name:'Chocolate Cake',cat:'Desserts',price:159,img:'https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=900&q=85',desc:'Rich chocolate cake for a sweet finish.',tag:'',ingredients:'Chocolate cake, cocoa, cream.'},
{id:18,name:'Brownie & Ice Cream',cat:'Desserts',price:189,img:'https://images.unsplash.com/photo-1563805042-7684c019e1cb?auto=format&fit=crop&w=900&q=85',desc:'Warm brownie with a scoop of ice cream.',tag:'Popular',ingredients:'Chocolate brownie, vanilla ice cream.'}
];
let cart=JSON.parse(localStorage.getItem('mazCart')||'[]'), activeCat='All';
const cats=['All','Burgers','Chicken','Fries','Combos','Drinks','Desserts'];
const $=s=>document.querySelector(s);
function renderCats(){ $('#categories').innerHTML=cats.map(c=>`<button class="cat ${c===activeCat?'active':''}" onclick="setCat('${c}')">${c}</button>`).join('');}
function setCat(c){activeCat=c;renderCats();renderProducts();}
function renderProducts(){const list=activeCat==='All'?products:products.filter(p=>p.cat===activeCat);$('#productGrid').innerHTML=list.map(p=>`<article class="product" onclick="openProduct(${p.id})"><div class="product-img"><img src="${p.img}" alt="${p.name}" loading="lazy">${p.tag?`<span class="tag">${p.tag}</span>`:''}</div><div class="product-info"><h3>${p.name}</h3><p>${p.desc}</p><div class="product-bottom"><span class="price">₹${p.price}</span><button class="order-mini" onclick="event.stopPropagation();addToCart(${p.id})">Order +</button></div></div></article>`).join('');}
function openProduct(id){const p=products.find(x=>x.id===id);$('#modalContent').innerHTML=`<button class="close" onclick="closeProduct()">×</button><div class="modal-product"><img src="${p.img}" alt="${p.name}"><div class="modal-body"><p class="eyebrow">${p.cat}</p><h2>${p.name}</h2><p>${p.desc}</p><p><b>Ingredients</b><br>${p.ingredients}</p><div class="extras"><label><input type="checkbox" value="49"> Extra cheese +₹49</label><label><input type="checkbox" value="29"> Extra sauce +₹29</label></div><div class="qty"><button onclick="changeModalQty(-1)">−</button><b id="modalQty">1</b><button onclick="changeModalQty(1)">+</button></div><button class="btn btn-primary full" onclick="addModalToCart(${p.id})">Add to Order · ₹<span id="modalPrice">${p.price}</span></button></div></div>`;$('#productModal').classList.add('open');$('#overlay').classList.add('open');window.modalBase=p.price;window.modalQty=1;updateModalPrice();}
function closeProduct(){$('#productModal').classList.remove('open');$('#overlay').classList.remove('open')}
function changeModalQty(n){window.modalQty=Math.max(1,window.modalQty+n);$('#modalQty').textContent=window.modalQty;updateModalPrice()}
function updateModalPrice(){const extra=[...document.querySelectorAll('.extras input:checked')].reduce((a,x)=>a+Number(x.value),0);$('#modalPrice').textContent=(window.modalBase+extra)*window.modalQty}
function addModalToCart(id){const p=products.find(x=>x.id===id);const extra=[...document.querySelectorAll('.extras input:checked')].reduce((a,x)=>a+Number(x.value),0);for(let i=0;i<window.modalQty;i++) addToCart(id,extra);closeProduct()}
function addToCart(id,extra=0){const p=products.find(x=>x.id===id);const key=id+'-'+extra;const item=cart.find(x=>x.key===key);if(item)item.qty++;else cart.push({key,id,extra,qty:1});saveCart();openCart()}
function saveCart(){localStorage.setItem('mazCart',JSON.stringify(cart));renderCart();$('#cartCount').textContent=cart.reduce((a,x)=>a+x.qty,0)}
function renderCart(){const el=$('#cartItems');if(!cart.length){el.innerHTML='<div class="empty">Your order is empty.<br>Add something seriously good.</div>';$('#cartTotal').textContent='₹0';return}el.innerHTML=cart.map(x=>{const p=products.find(p=>p.id===x.id);return `<div class="cart-line"><img src="${p.img}" alt=""><div class="cart-line-info"><b>${p.name}</b><small>₹${p.price+(x.extra||0)} each</small><div class="cart-controls"><button onclick="adjust('${x.key}',-1)">−</button><span>${x.qty}</span><button onclick="adjust('${x.key}',1)">+</button><button onclick="removeItem('${x.key}')">Remove</button></div></div></div>`}).join('');$('#cartTotal').textContent='₹'+cart.reduce((a,x)=>{const p=products.find(p=>p.id===x.id);return a+(p.price+(x.extra||0))*x.qty},0)}
function adjust(key,n){const i=cart.find(x=>x.key===key);if(!i)return;i.qty+=n;if(i.qty<=0)cart=cart.filter(x=>x!==i);saveCart()}
function removeItem(key){cart=cart.filter(x=>x.key!==key);saveCart()}
function openCart(){$('#cartDrawer').classList.add('open');$('#overlay').classList.add('open')}
function closeCart(){$('#cartDrawer').classList.remove('open');$('#overlay').classList.remove('open')}
function whatsappOrder(){if(!cart.length){openCart();return}const name=prompt('Customer name:');if(!name)return;const phone=prompt('Phone number:');if(!phone)return;const method=confirm('OK = Delivery\nCancel = Pickup')?'Delivery':'Pickup';const total=cart.reduce((a,x)=>{const p=products.find(p=>p.id===x.id);return a+(p.price+(x.extra||0))*x.qty},0);const lines=cart.map(x=>{const p=products.find(p=>p.id===x.id);return `• ${p.name} × ${x.qty} — ₹${(p.price+(x.extra||0))*x.qty}`}).join('%0A');const msg=`MAZ BURGER — NEW DEMO ORDER%0A%0ACustomer: ${encodeURIComponent(name)}%0APhone: ${encodeURIComponent(phone)}%0AType: ${method}%0A%0A${lines}%0A%0ATotal: ₹${total}%0A%0APlease confirm availability and final details.`;const number=localStorage.getItem('mazWhatsapp')||'0000000000';window.open('https://wa.me/'+number+'?text='+msg,'_blank')}
$('#cartOpen').onclick=openCart;$('#cartClose').onclick=closeCart;$('#overlay').onclick=()=>{closeCart();closeProduct()};$('#checkout').onclick=whatsappOrder;$('#heroOrder').onclick=whatsappOrder;$('#deliveryOrder').onclick=whatsappOrder;$('#contactOrder').onclick=whatsappOrder;
$('#menuToggle').onclick=()=>document.querySelector('nav').classList.toggle('mobile-open');
document.addEventListener('change',e=>{if(e.target.closest('.extras'))updateModalPrice()});
renderCats();renderProducts();saveCart();